runtime: nodejs16

env_variables:
  # insert SALT before deploy
  REACT_APP_SALT:
  REACT_APP_API_URL: https://wedding-backend-dot-nick-and-zoe-wedding.ts.r.appspot.com
  # insert API key before deploy
  REACT_APP_GOOGLE_API_KEY:
automatic_scaling:
  max_instances: 2
instance_class: F1
