runtime: custom
env: flex

env_variables:
  # insert SALT before deploy
  REACT_APP_SALT:
  REACT_APP_API_URL: https://wedding-backend-dot-nick-and-zoe-wedding.ts.r.appspot.com

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
