version: '3.7'
services:
  frontend:
    build: frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build: backend
    ports:
      - 4000:8080
    volumes:
      - ./backend:/app
      - /app/node_modules
