version: "3.7"
services:
  frontend:
    build: frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_SALT:
      REACT_APP_API_URL: http://localhost:4000
      REACT_APP_GOOGLE_API_KEY:
  backend:
    build: backend
    ports:
      - 4000:8080
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      SALT:
      SMTP:
      GOOGLE_APPLICATION_CREDENTIALS: /app/.gcp/nick-and-zoe-wedding-2848b778b1ff.json
